all:
  children:
    nord:
      hosts:
        jb-nord-01.steg.tn:
          ansible_host: 10.10.1.11
        jb-nord-04.steg.tn:
          ansible_host: 10.10.1.14
        jb-nord-07.steg.tn:
          ansible_host: 10.10.1.17
      vars:
        region_name: NORD
        jboss_home: /opt/jboss-eap
        jboss_instance_user: jboss
