all:
  children:
    sud:
      hosts:
        jb-sud-02.steg.tn:
          ansible_host: 10.20.1.12
        jb-sud-05.steg.tn:
          ansible_host: 10.20.1.15
      vars:
        region_name: SUD
        jboss_home: /opt/jboss-eap
        jboss_instance_user: jboss
